[build-system]
# NOTE: Keep this in sync with `requirements/dist-build-constraints.in`
# NOTE: at all times.
requires = [
    # Essentials
    "setuptools>=34.4",
]
build-backend = "setuptools.build_meta"
